title: RVA
org: Re-Volt America
email: jose@bgmp.cl
url: "https://re-volt-america.github.io/Website"
description: >-
  The Website for the Re-Volt America Community.
encoding: utf-8
markdown: kramdown

sass:
  sass_dir: assets/css

include:
  - _pages
  - _seasons

exclude:
  - README.md
  - LICENCE.md

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: seasons
    values:
      layout: default
  - scope:
      path: emoji/unicode
    values:
      emoji: true

emoji:
  src: "https://re-volt-america.github.io/Website" # /emoji/unicode

plugins:
  - jemoji
